### ISSUE TITLE
Flask 0.11 jsonify supports serializing more types

### ISSUE THREAD

**Issue by davidism** [skozlovf/flask-json#2]
Flask 0.11 removed the restriction on `jsonify` that only allowed dict at the top level.  Now any valid JSON type can be passed to `jsonify`.  Flask-JSON should relax its checks as well.

http://flask.pocoo.org/docs/0.11/api/#flask.json.jsonify

**Comment by mattdavis1121** [comment]
Hey! Wondering if this ever got any traction. If not, maybe I'll take a whack at it.

Thanks!

**Comment by skozlovf** [comment]
Yep, I plan to improve stuff as soon as find some time. The issue requires API changes. I'll try to work on it this weekend.

**Comment by mattdavis1121** [comment]
Totally get it. No rush. If you'd like a hand, let me know.

**Comment by skozlovf** [comment]
Thanks man)

**Comment by skozlovf** [comment]
Released new version 0.3.2

**Comment by mattdavis1121** [comment]
Woo! Thanks for knocking this out so quickly. Does this mean I can just pip upgrade to get the new version?

**Comment by skozlovf** [comment]
> Does this mean I can just pip upgrade
Yep.
