### ISSUE TITLE
Testing documentation needs to highlight changes needed to post data to a json endpoint

### ISSUE THREAD

**Issue by sc68cal** [skozlovf/flask-json#6]
The unit testing documentation covers doing GET requests to flask-json endpoints, but without documenting the changes that are required to the `test_client_class` attribute, users will try to POST data and end up getting `<JsonTestResponse streamed [400 BAD REQUEST]>` objects back.

https://github.com/skozlovf/flask-json/blob/d2db386f21648ad35d4b7a74cb55b5794785f9a2/tests/conftest.py#L12

**Comment by skozlovf** [comment]
Don't really get what you mean. Could you provide more info or example code?

**Comment by sc68cal** [comment]
Basically your documentation only show how to do a `GET` request in a unit test. You don't have any examples of a unit test where you POST data to a flask app. Doing it by using the default `response_class` and `test_client_class`(http://flask.pocoo.org/docs/1.0/api/#test-client) ends up failing because the standard test client doesn't serialize things correctly. Calling things like

```python
self.app.post('/SOME_ENDPOINT', MY_DATA)
```

Returns that `400 BAD REQUEST` error. 

Changing the unit tests to use your overidden `FlaskClient` with the `post_json` method and doing:

```python
self.app.post_json('/SOME_ENDPOINT', MY_DATA)
```

Gets past the bad request error

**Comment by skozlovf** [comment]
Should work in`0.4.0`.
