### ISSUE TITLE
[FEATURE] Add support for "json lines" / "ndjson"

### ISSUE THREAD

**Issue by mzpqnxow** [skozlovf/flask-json#8]
Hello, I'm wondering if you would implement or accept a PR to add something like `as_ndjson`, `as_jsonl` or `as_json_lines` decorators, to return a response in JSON Lines / NDJSON format? If you're not familiar with these, they're basically just line-based json- e.g. instead of:

```
[{"a": "b"}, {"a": "b"}, {"a": "b"}]
```

The format is:

```
{"a": "b"}
{"a": "b"}
{"a": "b"}
```

You might be wondering what the use-case is- in my case, it's very, very large JSON results files. This is not a problem from the server-side, but on the client side, I need to be able to process the file/stream iteratively, which is not something that can be done reliably or cleanly with traditional JSON

There is no standard agreed-upon mime-type for NDJSON as far as I know (some discussion [here](https://stackoverflow.com/questions/51690624/json-lines-mime-type)) so I think any of those would do

Thoughts on this? I'm happy to fork the project if you would rather not add this, but I feel that since it's a very small modification, is optional so it won't bother current users, and has very little cost to maintain it's a reasonable ask, especially as NDJSON becomes more popular (the ubiquitous `pandas` Python library has supported line-based JSON for a long time now, for precisely the use-case I'm describing above)

I can always of course just implement my own decorators in the same way that flask-json does, but it would be convenient and clean to add it to your project

Thanks, and thanks for you work on this!

EDIT: I'm looking at how you have json and jsonp implemented and I can see this would be a bit more invasive of a change than I thought.. so it's udnerstandable if you don't really want to get into this

**Comment by mzpqnxow** [comment]
I went ahead and implemented this (admittedly poorly, I threw it together in a couple of hours) if you're at all interested - https://github.com/mzpqnxow/flask-json/tree/ndjson

**Comment by skozlovf** [comment]
Hi.
Overall, I'm ok to add this feature. But I didn't use it before, so need to review. I'll check your implementation.

Thoughts.
You write you operate with very large JSONs, but seems you keep all of them in memory, then convert to string. As I understand key feature is streaming line-by-line. So, generally, there must be a generator creating JSON lines at runtime and endpoint will send one line at a time to response stream. There is smth to think about.

PS I'm super busy these days (or couple of months), so things will go slow.

**Comment by mzpqnxow** [comment]
Hey @skozlovf thanks for taking the time to reply. I understand you don't have time to work on this

I think for now it's best to keep what I have as a separate fork and branch because the code quality is so poor and the tests which I adapted from your JSONP tests need some work. If you do have time to review it that would be great, but don't spend more than 10-15 minutes on it

For now I will just use `constraints.txt` in my projects to use my fork from GH. Maybe at some point later after I have time to clean it up I can put a note here and see if you have time to consider it as a PR

Your code is very well written and the tests are very thoughtful and thorough so I don't want to pollute your project with my half-assed implementation ;)

Thanks again for taking the time to put a note here

**Comment by skozlovf** [comment]
Will see, if I'll have time then will implement in my way. Thanks for the request!

**Comment by mzpqnxow** [comment]
I've decided that the cruft this requires really isn't worthwhile. This can be closed

I'll still be using the project for the usual JSON responses, so thanks!

**Comment by skozlovf** [comment]
Great! Thank you.
