### ISSUE TITLE
Returns 'null' with empty dict in Flask 2.2.x

### ISSUE THREAD

**Issue by Dominick-Peluso-Bose** [skozlovf/flask-json#9]
I noticed when updating Flask to 2.2.x I now see `null` when the response JSON object is empty.

### Example
```py
from flask import Flask
from flask_json import FlaskJSON, as_json

app = Flask(__name__)
FlaskJSON(app)
app.config['JSON_ADD_STATUS'] = False

@app.route("/test-obj", methods=["GET"])
@as_json
def test_obj():
    return {}
```

### With Flask 2.1.3:

```sh
❯ curl -s  http://localhost:9003/test-obj | jq
{}
```

### With Flask 2.2.2:

```sh
❯ curl -s  http://localhost:9003/test-obj | jq
null
```

A workaround is to disable `JSON_ADD_STATUS` which will then return:

```sh
❯ curl -s  http://localhost:9003/test-obj | jq
{
  "status": 200
}
```

But of course, then you have that extra property in your API.

**Comment by skozlovf** [comment]
@Dominick-Peluso-Bose There are some JSON-related changes in the `flask` internals. Current  `flask-json` uses deprecated way and it will not work in the upcoming `flask  2.2.3`. I will update implementation as soon as I can (I hope before the release).
